init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

build_script:
  - mv .description DESCRIPTION
  - travis-tool.sh install_deps

test_script:
    - Rscript -e source(".ci_tests.R", echo=TRUE)

on_failure:
  - travis-tool.sh dump_logs
